#define GLI_INCLUDE_GL_AMD_QUERY_BUFFER_OBJECT

enum Main {

  GL_QUERY_BUFFER_AMD               = 0x9192,
  GL_QUERY_BUFFER_BINDING_AMD       = 0x9193,
  GL_QUERY_RESULT_NO_WAIT_AMD       = 0x9194,

};

